# Generated by Django 4.1.7 on 2023-02-21 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Five',
        ),
    ]
